version: '3.8'
services:
  backend:
    build: ./backend
    container_name: lms-backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: lms-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true   # 👈 add this line
      - CHOKIDAR_INTERVAL=200
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    container_name: lms-db
    restart: always
    environment:
      MYSQL_DATABASE: lms
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: lms-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data:
